language: python

python:
    - 3.6

sudo: enabled
before_install:
 - sudo apt-get update
 - sudo apt-get install -y git
 - sudo apt-get install -y python3 python3-dev python3-pip
 - sudo apt-get install -y curl

# install dependencies
install:
  - pip3 install -r requirements/dev.txt
  - pip3 install codecov

script:
  #PEP 8
  - flake8 bpm_projects_api --count
  #Tests and Coverage
  - coverage erase
  - coverage run -m pytest -v
  #75% of the code should be covered
  - coverage html --fail-under=75

after_success:
  - codecov
